
name: 2
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: idk


      run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip


    - name: 1
      run: Expand-Archive ngrok.zip
    - name: 2
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN

      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Update
      run: .\ngrok\ngrok.exe update
    - name: Update
      run: .\ngrok\ngrok.exe --version
    - name: Enable TS

      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0


    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"


    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1


    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "Passw0rd!" -Force)


    - name: 223
      run: .\ngrok\ngrok.exe tcp 3389
